version: '3'

services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    ports:
      - "8888:8080"
    environment:
      - BASE_URL=http://127.0.0.1:8888/
      - INSTANCE_NAME=LocalSearXNG
